version: "3.9"
services:
  pg:
    image: pgvector/pgvector:pg16
    container_name: troy_pg
    environment:
      POSTGRES_USER: troy
      POSTGRES_PASSWORD: troy
      POSTGRES_DB: kb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U troy -d kb"]
      interval: 5s
      timeout: 3s
      retries: 12
    volumes:
      - C:/troy-assistant/kb/schema/init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro

  adminer:
    image: adminer
    container_name: troy_adminer
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8080:8080"
